<?php

namespace Alotofus\HoonterWebBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WaitingStartupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WaitingStartupsRepository extends EntityRepository
{
}
