parameters:
#    alotofus_api.example.class: Alotofus\ApiBundle\Example

services:
#    alotofus_api.example:
#        class: %alotofus_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
